model:
  _target_: allegro.model.AllegroModel
  compile_mode: compile
  seed: 456
  model_dtype: float32
  type_names:
  - C
  - H
  - O
  - Cu
  r_max: 5.0
  radial_chemical_embed:
    _target_: allegro.nn.TwoBodyBesselScalarEmbed
    num_bessels: 8
    bessel_trainable: false
    polynomial_cutoff_p: 6
  radial_chemical_embed_dim: 64
  scalar_embed_mlp_hidden_layers_depth: 1
  scalar_embed_mlp_hidden_layers_width: 64
  scalar_embed_mlp_nonlinearity: silu
  l_max: 1
  num_layers: 2
  num_scalar_features: 64
  num_tensor_features: 32
  allegro_mlp_hidden_layers_depth: 1
  allegro_mlp_hidden_layers_width: 64
  allegro_mlp_nonlinearity: silu
  parity: true
  tp_path_channel_coupling: true
  readout_mlp_hidden_layers_depth: 1
  readout_mlp_hidden_layers_width: 64
  readout_mlp_nonlinearity: silu
  avg_num_neighbors: 14.476190476190476
  per_type_energy_shifts: -19318.36491328967
  per_type_energy_scales: 31.17627494170824
  per_type_energy_scales_trainable: false
  per_type_energy_shifts_trainable: false
  pair_potential:
    _target_: nequip.nn.pair_potential.ZBL
    units: real
    chemical_species:
    - C
    - H
    - O
    - Cu
optimizer:
  _target_: torch.optim.Adam
  lr: 0.001
lr_scheduler: null
loss:
  _target_: nequip.train.EnergyForceLoss
  per_atom_energy: true
  coeffs:
    total_energy: 1.0
    forces: 1.0
train_metrics: null
val_metrics:
  _target_: nequip.train.EnergyForceMetrics
  coeffs:
    per_atom_energy_mae: 1.0
    forces_mae: 1.0
test_metrics:
  _target_: nequip.train.EnergyForceMetrics
  coeffs:
    per_atom_energy_mae: 1.0
    forces_mae: 1.0
num_datasets:
  train: 1
  val: 1
  test: 1
  predict: 0
info_dict:
  versions:
    torch: 2.6.0+cu124
    e3nn: 0.5.8
    nequip: 0.16.1
    allegro: 0.8.0
  data:
    _target_: nequip.data.datamodule.sGDML_CCSD_DataModule
    dataset: aspirin
    data_source_dir: aspirin_data
    transforms:
    - _target_: nequip.data.transforms.ChemicalSpeciesToAtomTypeMapper
      model_type_names:
      - C
      - H
      - O
      - Cu
    - _target_: nequip.data.transforms.NeighborListTransform
      r_max: 5.0
    trainval_test_subset:
    - 40
    - 10
    train_val_split:
    - 30
    - 10
    seed: 123
    train_dataloader:
      _target_: torch.utils.data.DataLoader
      batch_size: 1
    val_dataloader:
      _target_: torch.utils.data.DataLoader
      batch_size: 5
    test_dataloader:
      _target_: torch.utils.data.DataLoader
      batch_size: 5
    stats_manager:
      _target_: nequip.data.CommonDataStatisticsManager
      type_names:
      - C
      - H
      - O
      - Cu
  trainer:
    _target_: lightning.Trainer
    max_epochs: 5
    log_every_n_steps: 5
    callbacks:
    - _target_: lightning.pytorch.callbacks.ModelCheckpoint
      dirpath: /home/dl/work/sg-qe-allegro-lammps-llzo-li/allegro/runs/20251226-155418
      save_last: true
  global_options:
    allow_tf32: false
  runs:
  - train
  - test
  training_module:
    _target_: nequip.train.EMALightningModule
    loss:
      _target_: nequip.train.EnergyForceLoss
      per_atom_energy: true
      coeffs:
        total_energy: 1.0
        forces: 1.0
    val_metrics:
      _target_: nequip.train.EnergyForceMetrics
      coeffs:
        per_atom_energy_mae: 1.0
        forces_mae: 1.0
    test_metrics:
      _target_: nequip.train.EnergyForceMetrics
      coeffs:
        per_atom_energy_mae: 1.0
        forces_mae: 1.0
    optimizer:
      _target_: torch.optim.Adam
      lr: 0.001
    model:
      _target_: allegro.model.AllegroModel
      compile_mode: compile
      seed: 456
      model_dtype: float32
      type_names:
      - C
      - H
      - O
      - Cu
      r_max: 5.0
      radial_chemical_embed:
        _target_: allegro.nn.TwoBodyBesselScalarEmbed
        num_bessels: 8
        bessel_trainable: false
        polynomial_cutoff_p: 6
      radial_chemical_embed_dim: 64
      scalar_embed_mlp_hidden_layers_depth: 1
      scalar_embed_mlp_hidden_layers_width: 64
      scalar_embed_mlp_nonlinearity: silu
      l_max: 1
      num_layers: 2
      num_scalar_features: 64
      num_tensor_features: 32
      allegro_mlp_hidden_layers_depth: 1
      allegro_mlp_hidden_layers_width: 64
      allegro_mlp_nonlinearity: silu
      parity: true
      tp_path_channel_coupling: true
      readout_mlp_hidden_layers_depth: 1
      readout_mlp_hidden_layers_width: 64
      readout_mlp_nonlinearity: silu
      avg_num_neighbors: 14.476190476190476
      per_type_energy_shifts: -19318.36491328967
      per_type_energy_scales: 31.17627494170824
      per_type_energy_scales_trainable: false
      per_type_energy_shifts_trainable: false
      pair_potential:
        _target_: nequip.nn.pair_potential.ZBL
        units: real
        chemical_species:
        - C
        - H
        - O
        - Cu
ema_decay: 0.999
