model:
  _target_: allegro.model.AllegroModel
  compile_mode: compile
  seed: 456
  model_dtype: float32
  type_names:
  - Li
  - La
  - Zr
  - O
  r_max: 5.0
  radial_chemical_embed:
    _target_: allegro.nn.TwoBodyBesselScalarEmbed
    num_bessels: 8
    bessel_trainable: false
    polynomial_cutoff_p: 6
  radial_chemical_embed_dim: 64
  scalar_embed_mlp_hidden_layers_depth: 1
  scalar_embed_mlp_hidden_layers_width: 64
  scalar_embed_mlp_nonlinearity: silu
  l_max: 1
  num_layers: 2
  num_scalar_features: 64
  num_tensor_features: 32
  allegro_mlp_hidden_layers_depth: 1
  allegro_mlp_hidden_layers_width: 64
  allegro_mlp_nonlinearity: silu
  parity: true
  tp_path_channel_coupling: true
  readout_mlp_hidden_layers_depth: 1
  readout_mlp_hidden_layers_width: 64
  readout_mlp_nonlinearity: silu
  avg_num_neighbors: 19.16796875
  per_type_energy_shifts: -0.017549121470548004
  per_type_energy_scales: 0.050026960607749964
  per_type_energy_scales_trainable: false
  per_type_energy_shifts_trainable: false
  pair_potential:
    _target_: nequip.nn.pair_potential.ZBL
    units: real
    chemical_species:
    - Li
    - La
    - Zr
    - O
optimizer:
  _target_: torch.optim.Adam
  lr: 0.001
lr_scheduler: null
loss:
  _target_: nequip.train.EnergyForceLoss
  per_atom_energy: true
  coeffs:
    total_energy: 1.0
    forces: 1.0
train_metrics: null
val_metrics:
  _target_: nequip.train.EnergyForceMetrics
  coeffs:
    per_atom_energy_mae: 1.0
    forces_mae: 1.0
test_metrics:
  _target_: nequip.train.EnergyForceMetrics
  coeffs:
    per_atom_energy_mae: 1.0
    forces_mae: 1.0
num_datasets:
  train: 1
  val: 1
  test: 1
  predict: 0
info_dict:
  versions:
    torch: 2.6.0+cu124
    e3nn: 0.5.8
    nequip: 0.16.1
    allegro: 0.8.0
  data:
    _target_: nequip.data.datamodule.ASEDataModule
    seed: 0
    split_dataset:
      file_path: dataset/train.extxyz
      train: 0.8
      val: 0.1
      test: 0.1
    transforms:
    - _target_: nequip.data.transforms.ChemicalSpeciesToAtomTypeMapper
      model_type_names:
      - Li
      - La
      - Zr
      - O
    - _target_: nequip.data.transforms.NeighborListTransform
      r_max: 5.0
    stats_manager:
      _target_: nequip.data.CommonDataStatisticsManager
      type_names:
      - Li
      - La
      - Zr
      - O
      dataloader_kwargs:
        batch_size: 32
    train_dataloader:
      _target_: torch.utils.data.DataLoader
      batch_size: 4
      shuffle: true
      num_workers: 4
    val_dataloader:
      _target_: torch.utils.data.DataLoader
      batch_size: 4
      num_workers: 4
    test_dataloader:
      _target_: torch.utils.data.DataLoader
      batch_size: 4
      num_workers: 4
  trainer:
    _target_: lightning.Trainer
    max_epochs: 5
    log_every_n_steps: 5
    callbacks:
    - _target_: lightning.pytorch.callbacks.ModelCheckpoint
      dirpath: /home/dl/work/sg-qe-allegro-lammps-llzo-li/allegro/runs/20251227-084122
      save_last: true
  global_options:
    allow_tf32: false
  runs:
  - train
  - test
  training_module:
    _target_: nequip.train.EMALightningModule
    loss:
      _target_: nequip.train.EnergyForceLoss
      per_atom_energy: true
      coeffs:
        total_energy: 1.0
        forces: 1.0
    val_metrics:
      _target_: nequip.train.EnergyForceMetrics
      coeffs:
        per_atom_energy_mae: 1.0
        forces_mae: 1.0
    test_metrics:
      _target_: nequip.train.EnergyForceMetrics
      coeffs:
        per_atom_energy_mae: 1.0
        forces_mae: 1.0
    optimizer:
      _target_: torch.optim.Adam
      lr: 0.001
    model:
      _target_: allegro.model.AllegroModel
      compile_mode: compile
      seed: 456
      model_dtype: float32
      type_names:
      - Li
      - La
      - Zr
      - O
      r_max: 5.0
      radial_chemical_embed:
        _target_: allegro.nn.TwoBodyBesselScalarEmbed
        num_bessels: 8
        bessel_trainable: false
        polynomial_cutoff_p: 6
      radial_chemical_embed_dim: 64
      scalar_embed_mlp_hidden_layers_depth: 1
      scalar_embed_mlp_hidden_layers_width: 64
      scalar_embed_mlp_nonlinearity: silu
      l_max: 1
      num_layers: 2
      num_scalar_features: 64
      num_tensor_features: 32
      allegro_mlp_hidden_layers_depth: 1
      allegro_mlp_hidden_layers_width: 64
      allegro_mlp_nonlinearity: silu
      parity: true
      tp_path_channel_coupling: true
      readout_mlp_hidden_layers_depth: 1
      readout_mlp_hidden_layers_width: 64
      readout_mlp_nonlinearity: silu
      avg_num_neighbors: 19.16796875
      per_type_energy_shifts: -0.017549121470548004
      per_type_energy_scales: 0.050026960607749964
      per_type_energy_scales_trainable: false
      per_type_energy_shifts_trainable: false
      pair_potential:
        _target_: nequip.nn.pair_potential.ZBL
        units: real
        chemical_species:
        - Li
        - La
        - Zr
        - O
ema_decay: 0.999
